### ISSUE TITLE
Size of LaTeX Package

### ISSUE THREAD

**Issue by jnayak1** [jnayak1/pdflatex-lambda#3]
One issue is that TeXLive, which compiles LaTeX documents, is very large. The full, portable version is about ~~500MB according to [this post](http://tex.stackexchange.com/questions/112734/is-is-possible-to-install-only-the-required-latex-tool-pdflatex-in-ubuntu)~~ 4.6GB.

This is a problem since Lambda limits the size of the zip file you can upload to [250MB unzipped](http://docs.aws.amazon.com/lambda/latest/dg/limits.html).

However, `pdflatex` depends on just a subset of the full version.

TODO:
- [x] Determine the subset of the full version of TeXLive needed to run `pdflatex`
- [x] How big is this subset?
- [x] How can we download and move this subset?

Approach:
- Research
- Boot up EC2 Amazon Linux instances and test

**Comment by jnayak1** [comment]
[Remove docs](http://tex.stackexchange.com/questions/66348/latex-minimal-installation-in-gnu-linux-distributions-e-g-in-ubuntu-and-using) to decrease TeXLive size

**Comment by jnayak1** [comment]
Portable version of TeXLive:
https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-420004.2
http://tex.stackexchange.com/questions/289206/what-is-meant-by-a-portable-tex-live-installation
http://tex.stackexchange.com/questions/329986/small-portable-linux-version-of-texlive  

-Intended to be put on a USB drive so that you can run all `texlive` commands without actually installing the packages
-Portable version is 4.6 GB!!
-2.0GB of this is docs
-1.7GB of this is fonts

**Comment by jnayak1** [comment]
"Almost every distro have its own package manager. Maintainers of any distro have their own point of view onto package building: its dependencies and its contents. So, for example, in Archlinux TeXLive is split onto many small packages. In Debian and Ubuntu, I think, it must be alike."[1](http://tex.stackexchange.com/questions/112734/is-is-possible-to-install-only-the-required-latex-tool-pdflatex-in-ubuntu)

**Comment by jnayak1** [comment]
"The only optimal way is to install texlive-core and after that - some packages you need (you will know that they aren't installed in your system by latex error messages)."[1](http://tex.stackexchange.com/questions/112734/is-is-possible-to-install-only-the-required-latex-tool-pdflatex-in-ubuntu)

**Comment by jnayak1** [comment]
There is no texlive-core available on Yum, the package manager on Amazon's Linux distribution, but general idea is probably the correct way to solve this problem. Start with the slimmest group of core packages and then add packages as needed.

**Comment by jnayak1** [comment]
Major TeXLive packages on Yum.
"
texlive-scheme-basic : basic scheme (plain and latex)
~~texlive-scheme-context : ConTeXt scheme~~
~~texlive-scheme-full : full scheme (everything)~~
~~texlive-scheme-gust : GUST TeX Live scheme~~
~~texlive-scheme-medium : medium scheme (small + more packages and languages)~~
~~texlive-scheme-minimal : minimal scheme (plain only)~~
~~texlive-scheme-small : small scheme (basic + xetex, metapost, a few languages)~~
~~texlive-scheme-tetex : teTeX scheme (more than medium, but nowhere near full)~~
~~texlive-scheme-xml : XML scheme~~
"[2](http://unix.stackexchange.com/questions/199638/how-to-fully-install-latex-in-fedora)
Link appears to be out of date

**Comment by jnayak1** [comment]
Additional TeXLive packages on Yum.
"
texlive-collection-basic : Essential programs and files
texlive-collection-bibtexextra : BibTeX additional styles
texlive-collection-binextra : TeX auxiliary programs
texlive-collection-context : ConTeXt and packages
texlive-collection-fontsextra : Additional fonts
texlive-collection-fontsrecommended : Recommended fonts
texlive-collection-fontutils : Graphics and font utilities
texlive-collection-formatsextra : Additional formats
texlive-collection-games : Games typesetting
texlive-collection-genericextra : Generic additional packages
texlive-collection-genericrecommended : Generic recommended packages
texlive-collection-htmlxml : HTML/SGML/XML support
texlive-collection-humanities : Humanities packages
texlive-collection-langafrican : African scripts
texlive-collection-langarabic : Arabic
texlive-collection-langcjk : Chinese/Japanese/Korean
texlive-collection-langcyrillic : Cyrillic
texlive-collection-langczechslovak : Czech/Slovak
texlive-collection-langenglish : US and UK English
texlive-collection-langeuropean : Other European languages
texlive-collection-langfrench : French
texlive-collection-langgerman : German
texlive-collection-langgreek : Greek
texlive-collection-langindic : Indic scripts
texlive-collection-langitalian : Italian
texlive-collection-langother : Other languages
texlive-collection-langpolish : Polish
texlive-collection-langportuguese : Portuguese
texlive-collection-langspanish : Spanish
texlive-collection-latex : LaTeX fundamental packages
texlive-collection-latexextra : LaTeX additional packages
texlive-collection-latexrecommended : LaTeX recommended packages
texlive-collection-luatex : LuaTeX packages
texlive-collection-mathextra : Mathematics packages
texlive-collection-metapost : MetaPost and Metafont packages
texlive-collection-music : Music packages
texlive-collection-omega : Omega packages
texlive-collection-pictures : Graphics, pictures, diagrams
texlive-collection-plainextra : Plain TeX packages
texlive-collection-pstricks : PSTricks
texlive-collection-publishers : Publisher styles, theses, etc
texlive-collection-science : Natural and computer sciences
texlive-collection-xetex : XeTeX and packages
"[2](http://unix.stackexchange.com/questions/199638/how-to-fully-install-latex-in-fedora)

**Comment by jnayak1** [comment]
Going to test `texlive-scheme-basic` on AWS EC2 instance:
- [x] How big is it?
- [ ] What are it's capabilities?
- [ ] What additional packages need to be added?

**Comment by jnayak1** [comment]
`texlive-scheme-basic` installs 171 total sub-packages:
https://docs.google.com/document/d/1PD5IaNDNnSoHgjm1u1N8bxkD_-LXBsDYZYGsi0wXIZE/edit

**Comment by jnayak1** [comment]
Yum calls `texlive-scheme-basic` a package group. The `texlive-scheme-basic` package group installs 171 total packages and dependencies.

**Comment by jnayak1** [comment]
Package group `texlive-scheme-basic` [is 157MB installed](https://docs.google.com/document/d/1PD5IaNDNnSoHgjm1u1N8bxkD_-LXBsDYZYGsi0wXIZE/edit).

**Comment by jnayak1** [comment]
Appears that it doesn't include popular package `Asmath` for my testing.

**Comment by mtl3jx** [comment]
`yum search texlive-collection` yields the following available packages:
- `texlive-collection-basic`
  - dependency of `texlive-scheme-basic`
- `texlive-collection-documentation-base`
  - installed with `texlive-scheme-basic`
  - We can remove this from the `texlive-scheme-basic` install
- `texlive-collection-fontsrecommended`
  - 27 packages 103 MB on top of `texlive-scheme-basic`
  - dependency of `texlive`
- `texlive-collection-htmlxml`
  - 37 packages 117 MB on top of `texlive-scheme-basic`
- `texlive-collection-latex`
  - installed with `texlive-scheme-basic`
- `texlive-collection-latexrecommended`
- `texlive-collection-xetex`
  - 61 packages 83 MB on top of `texlive`

**Comment by jnayak1** [comment]
Installed size of yum package `texlive` with dependencies is 268MB. This is over the 250MB limit for AWS Lambda.

**Comment by jnayak1** [comment]
`texlive` package includes `texlive-scheme-basic` along with:
- `texlive-collection-latexrecommended`
  - 111 MB
  - [61packages](https://github.com/jnayak1/pdflatex-lambda/blob/master/texlive-collection-latexrecommended-dependencies.txt)

**Comment by jnayak1** [comment]
"XeLaTeX (xetex) is essentially a replacement for pdfLaTeX. It was primarily developed to enable better font handling, especially non-Roman scripts. If you want to write in Telugu, then XeLaTeX is going to make your life much easier. For English writers, the main benefit of XeLaTeX is the ability to use the fonts on your computer, just as you can with other software. If you’ve grown to love using Georgia in MS-Word and always wanted to write a LaTeX document in Georgia, now you can."[3](http://robjhyndman.com/hyndsight/xelatex/)

**Comment by jnayak1** [comment]
"lua(la)tex has been choosen as the official successor of pdf(la)tex, so you can expect more development effort to go towards it now and in the future. For example, microtype supports much more features under lua(la)tex than it does under xe(la)tex,"[4](http://tex.stackexchange.com/questions/126206/why-choose-lualatex-over-xelatex)

**Comment by jnayak1** [comment]
"Another advantage of LuaTeX over XeTeX is that LuaTeX uses the PDF engine of pdfTeX, while XeTeX uses its own one."[4](http://tex.stackexchange.com/questions/126206/why-choose-lualatex-over-xelatex)

**Comment by jnayak1** [comment]
`texlive-luatex` is included with `texlive-scheme-basic`

**Comment by jnayak1** [comment]
Using TeXLive installer instead of Yum package installer. It has a text gui that allows you to select which packages you want to download and where you want to download them to.
