### ISSUE TITLE
Create script to setup TeXLive

### ISSUE THREAD

**Issue by jnayak1** [jnayak1/pdflatex-lambda#9]
Create a script that:
- [ ] Downloads the [TeXLive installer](http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz)
- [ ] Runs the [text gui installer](https://www.tug.org/texlive/quickinstall.html) allowing user to select what packages they want to install, where they want to install them to, etc.
- [ ] Adds /path/to/package/bin/x86_64-linux to PATH

Also:
- [ ] Look into the TeXLive perltk installer. That might give more options/customizability than the text gui installer.

**Comment by dmlittle** [comment]
@jnayak1 did you ever manage to get pdflatex working on AWS Lambda?

**Comment by jnayak1** [comment]
@dmlittle  Lambda has limits on the size of the package. I had problems with getting the size of package small enough so no
